### ISSUE TITLE
[feature] Prevent files from being overwritten

### ISSUE THREAD

**Issue by LiZeC123** [helloShen/leetcode-helper#6]
Today I used this project to create a folder for a question. When I was ready to do the next question, I modified the configuration file, but forgot to save it. So when I executed the create command `ant generate`, the new file created overwrites my original code file. 

Therefore, you should check if the specified file exists before creating a new file. I don't know much about how `ant` works, so I can't implement this feature myself, but this article may be helpful to you. 

[Do I have a way to check the existence of a directory in Ant (not a file)? 
](https://stackoverflow.com/questions/1163998/do-i-have-a-way-to-check-the-existence-of-a-directory-in-ant-not-a-file)

**Comment by LiZeC123** [comment]
And This story tells us that all the code files should be managed under git.  sad  :cold_sweat:

**Comment by helloShen** [comment]
Nice tips, let me fix it, thx.

**Comment by helloShen** [comment]
Problem fixed. Let me know if anything wrong.

**Comment by LiZeC123** [comment]
This update solves many problems and there are no problems at present.
